# Generated by Django 4.1.1 on 2024-08-30 20:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('entrypoint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='API',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('key', models.CharField(default='OsVNQXC3IOuZrlXxhX48dU6BQYjO7Q7yUNoj', max_length=255, unique=True)),
                ('prefix', models.CharField(default='api', max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('system', models.CharField(max_length=255)),
                ('module', models.CharField(max_length=255)),
                ('actor', models.CharField(max_length=255)),
                ('function', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'api',
            },
        ),
    ]
